### ISSUE TITLE
Decentralized DNS, based on EmerCoin distributed services

### ISSUE THREAD

**Issue by maxihatop** [hyperboria/hyperboria.github.io#2]
Здравствуйте, прочёл статью: http://habrahabr.ru/post/182652/
Там Вы написали о текущих проблемах:

> Сейчас выбираются программные движки для создания следующих сервисов:
> 1) Децентрализованный DNS (скорее всего namecoin / P2P DNS)

Я хочу предложить к рассмотрению распределённый децентрализованый DNS, базирующийся на EmerCoin: http://emercoin.com/DNS_and_Name-Value_Storage

Чем EmerCoin DNS лучше аналогичного сервиса от Namecoin or NXT?
1. Каждый кошелёк является нативным DNS-сервером стандарта RFC1034
2. Поддерживается не одна фиксированая TLD-зона _.bit, a четыре (_.lib *.emc *.coin *.bazar), c возможностью добавления новых.
3. Хранилище NVS может быть использовано для ряда других сервисов, предложенных в документе выше.
4. Некоторые уникальные сервисы уже написаны и успешно эксплуатируются (emcssl, emcssh, infocard)
5. Бесплатная и дружественная поддержка от EmerCoin team. Просто напишите на team(symbol)emercoin.com, и Вам с радостью помогут.

**Comment by ghost** [comment]
Can anyone translate? Is this a similar proposal to https://github.com/Tribler/tribler/issues/1455?

@shnatsel

**Comment by maxihatop** [comment]
Oh, I will translate. Is not 100% similar, but very close - EMC supports distributed DNS, and we would like propose our DNS system for your consideration. For details about our DNS, see: http://emercoin.com/DNS_and_Name-Value_Storage
Translated text will be ready soon. Sorry for wrong language.

**Comment by maxihatop** [comment]
TRANSLATED:

Hi,

I read articles about hyperborea project, on the wiki https://wiki.projectmeshnet.org/DNS#Current_state_of_DNS_on_Hyperboria
I see: There isn't a decentralized solution yet.

I would like propose for consideration to use in the your project EmerCoin decentralized DNS system.
See description here: http://emercoin.com/DNS_and_Name-Value_Storage

Why to use EmerCoin DNS  better, than Namecoin or NXT?
1. Every EMC wallet is native RFC1034 DNS server. Thus, all programs can send DNS-request directly to the local wallet. In addition, EmerCoin has peering agreement with OpenNIC alternative
   DNS community. Thus, our DNS-zones available from any computer, using DNS-server(s), participating in the OpenNIC network. 
2. Currently supported 4 TLD zones (*.lib *.emc *.coin *.bazar), with possibility to add a new zones.
   Namecoin support only single zone, *.bit. NXT spec very broad, and there is not exact instruction, how to create and retrieve NS-records and domains.
3. EmerCoin NVS can be used for broad set of another services, specified in the document above.
4. Some unique EMC-based services (emcssl, emcssh, infocard) already implemented and running in production.
   You can use them too, if you found them suitable for your purposes.
5. Free and friendly support from  EmerCoin team. Just write to team(symbol)emercoin.com, and we will be glad to help you.

**Comment by Shnatsel** [comment]
There is a design document on a distributed DNS solution internally. In a nutshell, it's a layer on top of namecoin, where namecoin is used only for storage of arbitrary data in the blockchain and the rest is implemented by our layer. This invalidates all the advantages listed above.

http://emercoin.com/DNS_and_Name-Value_Storage provides a good overview of EmerCoin. According to it, the differences from NameCoin are:
- Partly Proof-of-Stake, partly Proof-of-Work
- Longer names allowed (512 instead of 255 bytes)
- Longer values allowed (20*1024 instead of 1023 bytes)
- Variable lease time, price depends on requested lease time
- As an anti-squatting measure, registering a new name is more expensive than renewing an existing one. However, it's expected to last for about 6 months.
- Supports name deletion for free.

Unless EmerCoin implements secure name resolution without requiring to store the entire blockchain locally, it's not a dramatic improvement over NameCoin for our use case, but still worth considering.

**Comment by ghost** [comment]
Okay, interesting, thanks for your interested in Hyperboria. Feel free to add it to the DNS notes: https://github.com/hyperboria/docs/blob/master/notes/dns.md

Or deploy a node in Hyperboria!

Gonna close this issue since it's unrelated to the website.
